version: '3'
services:
  app:
    container_name: kcbc-streaming-server-app
    build:
      context: ./nodejs-app
      dockerfile: Dockerfile-app
    expose:
      - 3000
    volumes:
      - ./nodejs-app:/home/nodeapp
      - /home/nodeapp/node_modules
      - hls:/home/nodeapp/hls
    working_dir: /home/nodeapp
    command: [sh, -c, node ./app.js]

  nginx:
    container_name: kcbc-streaming-server-nginx
    build:
      context: ./nginx
      dockerfile: Dockerfile-nginx
    ports:
      - 80:80
      - 443:443
      - 1935:1935
    volumes:
      - hls:/home/nodeapp/hls
    environment:
      - DOMAIN="studio.k.kumamoto-nct.ac.jp"
volumes:
  hls: